oracleConnection:
  connectString: centosdb
  user: provendb
  password: provendbdummy
oracleTables:
  - username.tablename
anchorType: HEDERA_MAINNET
dbmsAlert: 'TRUE'
proofable:
  token: YourTokenHere
  endpoint: 'api.proofable.io:443'
