---
platform: linux
image_resource:
  type: docker-image
  source: { repository: alpine/git, tag: latest }
inputs:
  - name: provendb-oracle
outputs:
  - name: provendb-oracle
run:
  path: ash
  args:
    - -exc
    - |
      cd provendb-oracle
      current_branch=$(git branch | grep hotfix/*)
      current_branch=$(echo $current_branch | sed 's/.*hotfix\///')
      last_commit=$(git rev-parse --short=7 HEAD)
      docker_tag="hotfix-${last_commit}-${current_branch}"
      echo "$docker_tag" > docker_tag
