# @Author: Michael Harrison (Mike@Southbanksoftware.com)
# @Date:   2020-03-06T10:03:40+11:00
# @Last modified by:   Michael Harrison
# @Last modified time: 2020-03-06T10:05:54+11:00

platform: linux
image_resource:
  type: docker-image
  source: { repository: node, tag: 12 }
inputs:
  - name: version
  - name: provendb-oracle
outputs:
  - name: provendb-oracle
params:
  GIT_ACCESS_TOKEN: ((common.git-access-token))
run:
  path: sh
  args:
    - -exc
    - |
      export APP_VERSION=$(cat version/number)
      git config --global url."https://${GIT_ACCESS_TOKEN}:@github.com/".insteadOf "https://github.com/"
      cd provendb-oracle
      yarn install
      yarn build
