# How to connect to Oracle
oracleConnection:
  connectString: 0.0.0.0:1521/orclcdb
  user: system
  password: oracle
#oracleTables:
#  - SYSTEM.CONTRACTSTABLE
anchorType: HEDERA_MAINNET
dbmsAlert: FALSE
proofable:
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MDMxNTA4OTIsImp0aSI6IkRtSHd5Q05TSUVZTERrYlk3dE1DWXRHVExabDFMQjM2S2lmbWtDN1JDNGs9Iiwic3ViIjoidTQ0eGl0dXhjbHZkdXRrNzg0aDI3cTlqIn0.ujgEZKfWn4Db4C-8geggu9fOUuS6B4iTpgkDuETwx0w
  endpoint: api.dev.proofable.io:443
