# @Author: Michael Harrison (Mike@Southbanksoftware.com)
# @Date:   2020-03-06T10:03:21+11:00
# @Last modified by:   Michael Harrison
# @Last modified time: 2020-03-06T10:32:08+11:00

# update pipeline:
# fly -t dev sp -c pipeline-deploy.yml -p provendb-oracle-deploy

resource_types:
  - name: meta
    type: docker-image
    source:
      repository: swce/metadata-resource
  - name: slack-alert
    type: docker-image
    source:
      repository: southbanksoftware/concourse-slack-alert-resource
  - name: github-status
    type: docker-image
    source:
      repository: dpb587/github-status-resource
      tag: master
  - name: gcs-resource
    type: docker-image
    source:
      repository: frodenas/gcs-resource

resources:
  - name: meta
    type: meta
  - name: slack
    type: slack-alert
    source:
      url: ((common.slack-webook-url))
  - name: github-status
    type: github-status
    source:
      repository: SouthbankSoftware/provendb-oracle
      access_token: ((common.git-access-token))
      branch: main
      context: deploy
  - name: provendb-oracle
    type: git
    check_every: 5m
    webhook_token: ((common.webhook-token))
    source:
      uri: https://github.com/SouthbankSoftware/provendb-oracle.git
      branch: main
      username: ((common.git-username))
      password: ((common.git-password))
      disable_ci_skip: false
  - name: provendb-releases
    type: git
    source:
      uri: https://github.com/SouthbankSoftware/provendb-releases.git
      branch: master
      username: ((common.git-username))
      password: ((common.git-password))
      disable_ci_skip: false
  - name: version
    type: semver
    source:
      driver: gcs
      bucket: provendb-ci
      json_key: ((common.service-account))
      key: provendb-oracle/version/version.txt
      initial_version: 0.0.0
  - name: release-darwin_amd64
    type: gcs-resource
    source:
      bucket: provendb-dev
      json_key: ((common.service-account))
      versioned_file: provendb-oracle/provendb-oracle_darwin_amd64
  - name: release-linux_amd64
    type: gcs-resource
    source:
      bucket: provendb-dev
      json_key: ((common.service-account))
      versioned_file: provendb-oracle/provendb-oracle_linux_amd64
  - name: release-windows_amd64
    type: gcs-resource
    source:
      bucket: provendb-dev
      json_key: ((common.service-account))
      versioned_file: provendb-oracle/provendb-oracle_windows_amd64.exe
  - name: docker-registry
    type: docker-image
    source:
      repository: asia.gcr.io/provendb/provendb-oracle
      username: _json_key
      password: ((common.service-account))

jobs:
  - name: build-and-deploy
    serial: true
    plan:
      - get: provendb-oracle
        trigger: true
      - put: github-status
        params:
          commit: provendb-oracle
          state: pending
      - get: version
      - task: build
        file: provendb-oracle/ci/tasks/task-build.yml
      - in_parallel:
          fail_fast: true
          limit: 3
          steps:
            - put: release-darwin_amd64
              params:
                file: provendb-oracle/provendb-oracle_darwin_amd64
                predefined_acl: publicRead
                cache_control: no-cache, max-age=0
            - put: release-linux_amd64
              params:
                file: provendb-oracle/provendb-oracle_linux_amd64
                predefined_acl: publicRead
                cache_control: no-cache, max-age=0
            - put: release-windows_amd64
              params:
                file: provendb-oracle/provendb-oracle_windows_amd64.exe
                predefined_acl: publicRead
                cache_control: no-cache, max-age=0
      - put: docker-registry
        params:
          build: provendb-oracle
          tag_file: version/number
          tag_as_latest: true
        get_params: { skip_download: true }
      - get: meta
      - get: provendb-releases
        params: { clean_tags: true }
      - task: save-build-info
        file: provendb-oracle/ci/tasks/task-save-build-info.yml
      - put: provendb-releases
        params:
          repository: provendb-releases
          rebase: true
      - put: version
        params:
          bump: patch
    on_failure:
      do:
        - put: slack
          params:
            alert_type: failed
            text: ((slack.guan))
        - put: github-status
          params:
            commit: provendb-oracle
            state: failure
    on_abort:
      do:
        - put: slack
          params:
            alert_type: failed
            text: Aborted. ((slack.guan))
        - put: github-status
          params:
            commit: provendb-oracle
            state: failure
    on_success:
      do:
        - put: slack
          params:
            alert_type: success
        - put: github-status
          params:
            commit: provendb-oracle
            state: success
