SET SERVEROUTPUT ON;

DECLARE
  v_Return NUMBER;
BEGIN
  v_Return := F_ANCHORREQUEST(
    TABLENAME => 'FABHUMS.EVENT_PAYLOAD',
    COLUMNLIST => 'PAYLOAD,CREATED_DATE',
    WHERECLAUSE => 'ID BETWEEN 0 and 14850',
    KEYCOLUMN => 'ID'
  );
 DBMS_OUTPUT.PUT_LINE('RequestID = ' || v_Return);
END;
/
